export const scorecard = [
  {
    team: "Australia",
    innings: {
      score: "180-10",
      overs: 56.5,
      run_rate: 3.17,
      extras: {
        total: 3,
        byes: 0,
        leg_byes: 2,
        wides: 0,
        no_balls: 1,
        penalty: 0,
      },
      batters: [
        {
          name: "Sam Konstas",
          dismissal: "lbw b Shamar Joseph",
          runs: 3,
          balls: 14,
          fours: 0,
          sixes: 0,
          strike_rate: 21.43,
        },
        {
          name: "Usman Khawaja",
          dismissal: "c Shai Hope b Shamar Joseph",
          runs: 47,
          balls: 128,
          fours: 4,
          sixes: 1,
          strike_rate: 36.72,
        },
        {
          name: "Cameron Green",
          dismissal: "c Justin Greaves b Shamar Joseph",
          runs: 3,
          balls: 21,
          fours: 0,
          sixes: 0,
          strike_rate: 14.29,
        },
        {
          name: "Josh Inglis",
          dismissal: "c Shai Hope b Jayden Seales",
          runs: 5,
          balls: 15,
          fours: 0,
          sixes: 0,
          strike_rate: 33.33,
        },
        {
          name: "Travis Head",
          dismissal: "c Shai Hope b Justin Greaves",
          runs: 59,
          balls: 78,
          fours: 9,
          sixes: 0,
          strike_rate: 75.64,
        },
        {
          name: "Beau Webster",
          dismissal: "b Shamar Joseph",
          runs: 11,
          balls: 24,
          fours: 1,
          sixes: 0,
          strike_rate: 45.83,
        },
        {
          name: "Alex Carey",
          dismissal: "c Roston Chase b Jayden Seales",
          runs: 8,
          balls: 15,
          fours: 1,
          sixes: 0,
          strike_rate: 53.33,
        },
        {
          name: "Pat Cummins",
          dismissal: "c Kraigg Brathwaite b Jayden Seales",
          runs: 28,
          balls: 18,
          fours: 3,
          sixes: 1,
          strike_rate: 155.56,
        },
        {
          name: "Mitchell Starc",
          dismissal: "c Justin Greaves b Jayden Seales",
          runs: 0,
          balls: 5,
          fours: 0,
          sixes: 0,
          strike_rate: 0.0,
        },
        {
          name: "Nathan Lyon",
          dismissal: "Not Out",
          runs: 9,
          balls: 17,
          fours: 1,
          sixes: 0,
          strike_rate: 52.94,
        },
        {
          name: "Josh Hazlewood",
          dismissal: "c Shai Hope b Jayden Seales",
          runs: 4,
          balls: 7,
          fours: 0,
          sixes: 0,
          strike_rate: 57.14,
        },
      ],
      bowlers: [
        {
          name: "Jayden Seales",
          overs: 15.5,
          maidens: 1,
          runs: 60,
          wickets: 5,
          economy: 3.79,
        },
        {
          name: "Shamar Joseph",
          overs: 16.0,
          maidens: 3,
          runs: 46,
          wickets: 4,
          economy: 2.88,
        },
        {
          name: "Alzarri Joseph",
          overs: 12.0,
          maidens: 3,
          runs: 37,
          wickets: 0,
          economy: 3.08,
        },
        {
          name: "Roston Chase",
          overs: 4.0,
          maidens: 0,
          runs: 9,
          wickets: 0,
          economy: 2.25,
        },
        {
          name: "Justin Greaves",
          overs: 9.0,
          maidens: 2,
          runs: 26,
          wickets: 1,
          economy: 2.89,
        },
      ],
      fall_of_wickets: [
        {
          batter: "Sam Konstas",
          score: "8/1",
          over: "3.4",
        },
        {
          batter: "Cameron Green",
          score: "14/2",
          over: "9.4",
        },
        {
          batter: "Josh Inglis",
          score: "22/3",
          over: "15.1",
        },
        {
          batter: "Usman Khawaja",
          score: "111/4",
          over: "39.4",
        },
        {
          batter: "Beau Webster",
          score: "123/5",
          over: "43.6",
        },
        {
          batter: "Alex Carey",
          score: "138/6",
          over: "48.4",
        },
        {
          batter: "Travis Head",
          score: "142/7",
          over: "49.2",
        },
        {
          batter: "Mitchell Starc",
          score: "143/8",
          over: "50.2",
        },
        {
          batter: "Pat Cummins",
          score: "170/9",
          over: "54.4",
        },
        {
          batter: "Josh Hazlewood",
          score: "180/10",
          over: "56.5",
        },
      ],
    },
  },
  {
    team: "WI",
    innings: {
      score: "180-10",
      overs: 56.5,
      run_rate: 3.17,
      extras: {
        total: 3,
        byes: 0,
        leg_byes: 2,
        wides: 0,
        no_balls: 1,
        penalty: 0,
      },
      batters: [
        {
          name: "Sam Konstas",
          dismissal: "lbw b Shamar Joseph",
          runs: 3,
          balls: 14,
          fours: 0,
          sixes: 0,
          strike_rate: 21.43,
        },
        {
          name: "Usman Khawaja",
          dismissal: "c Shai Hope b Shamar Joseph",
          runs: 47,
          balls: 128,
          fours: 4,
          sixes: 1,
          strike_rate: 36.72,
        },
        {
          name: "Cameron Green",
          dismissal: "c Justin Greaves b Shamar Joseph",
          runs: 3,
          balls: 21,
          fours: 0,
          sixes: 0,
          strike_rate: 14.29,
        },
        {
          name: "Josh Inglis",
          dismissal: "c Shai Hope b Jayden Seales",
          runs: 5,
          balls: 15,
          fours: 0,
          sixes: 0,
          strike_rate: 33.33,
        },
        {
          name: "Travis Head",
          dismissal: "c Shai Hope b Justin Greaves",
          runs: 59,
          balls: 78,
          fours: 9,
          sixes: 0,
          strike_rate: 75.64,
        },
        {
          name: "Beau Webster",
          dismissal: "b Shamar Joseph",
          runs: 11,
          balls: 24,
          fours: 1,
          sixes: 0,
          strike_rate: 45.83,
        },
        {
          name: "Alex Carey",
          dismissal: "c Roston Chase b Jayden Seales",
          runs: 8,
          balls: 15,
          fours: 1,
          sixes: 0,
          strike_rate: 53.33,
        },
        {
          name: "Pat Cummins",
          dismissal: "c Kraigg Brathwaite b Jayden Seales",
          runs: 28,
          balls: 18,
          fours: 3,
          sixes: 1,
          strike_rate: 155.56,
        },
        {
          name: "Mitchell Starc",
          dismissal: "c Justin Greaves b Jayden Seales",
          runs: 0,
          balls: 5,
          fours: 0,
          sixes: 0,
          strike_rate: 0.0,
        },
        {
          name: "Nathan Lyon",
          dismissal: "Not Out",
          runs: 9,
          balls: 17,
          fours: 1,
          sixes: 0,
          strike_rate: 52.94,
        },
        {
          name: "Josh Hazlewood",
          dismissal: "c Shai Hope b Jayden Seales",
          runs: 4,
          balls: 7,
          fours: 0,
          sixes: 0,
          strike_rate: 57.14,
        },
      ],
      bowlers: [
        {
          name: "Jayden Seales",
          overs: 15.5,
          maidens: 1,
          runs: 60,
          wickets: 5,
          economy: 3.79,
        },
        {
          name: "Shamar Joseph",
          overs: 16.0,
          maidens: 3,
          runs: 46,
          wickets: 4,
          economy: 2.88,
        },
        {
          name: "Alzarri Joseph",
          overs: 12.0,
          maidens: 3,
          runs: 37,
          wickets: 0,
          economy: 3.08,
        },
        {
          name: "Roston Chase",
          overs: 4.0,
          maidens: 0,
          runs: 9,
          wickets: 0,
          economy: 2.25,
        },
        {
          name: "Justin Greaves",
          overs: 9.0,
          maidens: 2,
          runs: 26,
          wickets: 1,
          economy: 2.89,
        },
      ],
      fall_of_wickets: [
        {
          batter: "Sam Konstas",
          score: "8/1",
          over: "3.4",
        },
        {
          batter: "Cameron Green",
          score: "14/2",
          over: "9.4",
        },
        {
          batter: "Josh Inglis",
          score: "22/3",
          over: "15.1",
        },
        {
          batter: "Usman Khawaja",
          score: "111/4",
          over: "39.4",
        },
        {
          batter: "Beau Webster",
          score: "123/5",
          over: "43.6",
        },
        {
          batter: "Alex Carey",
          score: "138/6",
          over: "48.4",
        },
        {
          batter: "Travis Head",
          score: "142/7",
          over: "49.2",
        },
        {
          batter: "Mitchell Starc",
          score: "143/8",
          over: "50.2",
        },
        {
          batter: "Pat Cummins",
          score: "170/9",
          over: "54.4",
        },
        {
          batter: "Josh Hazlewood",
          score: "180/10",
          over: "56.5",
        },
      ],
    },
  },
];